# /etc/netplan/00-installer-config.yaml
# sudo netplan apply

network:
  version: 2
  renderer: networkd
  ethernets:
    ens18: 
      dhcp4: no
      addresses:
        - 10.100.100.11/24
      routes:
        - to: default
          via: 10.100.100.1   
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
